"""Reviewed US campus census. Facts are transcribed, never inferred from spend/GPU counts.

Run after a manual source review to regenerate the curated JSON. This is a purposive
sample of named US projects, not every data center worldwide or a statistical sample.
Raw acquisition is independent: fetch_datacenters.py records failures and hashes.
"""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]
old=json.loads((R/'public/data/workspace.json').read_text(encoding='utf-8'))
sources={s['id']:s for s in old['sources']}
new=[]
def source(id,title,url,date,locator):
    s=dict(id=id,title=title,url=url,published=date,accessed='2026-10-06',locator=locator,review='Primary publisher material reviewed; announcement is guidance, not completed capacity.',status='Public source reviewed')
    sources[id]=s;new.append(s)
source('dc_crusoe_report','Crusoe 2025 impact report','https://media.ffycdn.net/us/crusoe/PL5TuZz5apXB9pVsd3H1.pdf','2026-05-28','Key sites: original Abilene 1.2 GW, Microsoft 900 MW, Claude 900 MW; construction status')
source('dc_crusoe_childress','Crusoe / Lancium Childress announcement','https://www.crusoe.ai/resources/newsroom/crusoe-and-lancium-announce-1-gigawatt-ai-data-center-campus-in-childress-texas','2026-07-15','1 GW grid-connected campus; Q3 2026 is construction start, not first power')
source('dc_lancium_childress','Lancium Childress interconnection','https://lancium.com/locations-childress-county/',None,'1 GW interconnect approved by ERCOT; no customer-ready month stated')
source('dc_cheyenne','Black Hills Cheyenne project update','https://ir.blackhillscorp.com/news-releases/news-release-details/black-hills-corp-provides-update-18-gigawatt-project-cheyenne',None,'1.8 GW project; early 2028 service; April equipment procurement agreement; Crusoe no longer partner')
source('dc_iren_q2','IREN Q2 FY26 update','https://irisenergy.gcs-web.com/news-releases/news-release-details/iren-reports-q2-fy26-results','2026-02-05','1.6 GW Oklahoma campus; grid studies complete, power ramp from 2028')
source('dc_iren_annual','IREN FY2026 Form 10-K','https://www.sec.gov/Archives/edgar/data/1878848/000187884826000052/iren-20260630.htm','2026-08-27','US campuses: Childress 750 MW, Sweetwater 1 1,400 MW and Sweetwater 2 600 MW; grid-connected capacity')
source('dc_iren_may','IREN May 2025 monthly update','https://iren.gcs-web.com/news-releases/news-release-details/iren-may-2025-monthly-update',None,'Earlier utility targets: Sweetwater 1 April 2026, Sweetwater 2 late 2027; historical targets, not current guarantees')
source('dc_iren_fy26','IREN FY26 results','https://irisenergy.gcs-web.com/news-releases/news-release-details/iren-reports-fy26-results','2026-08-27','Horizon 1 delivered; Horizons 2–4 target Q4 2026; 0.8 GW IT cumulative 2027 across platform, not one site')
source('dc_hut_q2','Hut 8 Q2 2026 results','https://www.hut8.com/news-insights/press-releases/hut-8-reports-second-quarter-2026-results',None,'River Bend 330 MW utility / 245 MW IT, Q2 2027; Beacon Point 1,000 MW utility / 704 MW IT, phased 2027; initial energization Q1 2027')
source('dc_apld_q3','Applied Digital Q3 FY26 results','https://ir.applieddigital.com/news-events/press-releases/detail/148/applied-digital-reports-fiscal-third-quarter-2026-results','2026-04-08','PF1 400 MW IT total, 100 operational; PF2 200 contracted IT; Delta Forge 1 430 MW electrical / 300 MW IT, initial mid-2027')
source('dc_apld_df2','Applied Digital Delta Forge 2 lease','https://ir.applieddigital.com/news-events/press-releases/detail/154/applied-digital-signs-210-mw-lease-at-delta-forge-2','2026-06-08','210 MW critical IT, Q1 2028 initial operations; portfolio utility power is grid-connected')
source('dc_wulf_q2','TeraWulf Q2 2026 results','https://investors.terawulf.com/news-events/press-releases/detail/144/terawulf-reports-second-quarter-2026-results','2026-08-05','Campus updates: Lake Mariner 438 MW IT contracted, Justified 401 IT, Muskie 1 GW electricity Q4 2028, Lake Hawkeye ~2029, Chesapeake ~2030')
source('dc_wulf_abernathy','TeraWulf FY2025 results / Abernathy','https://www.sec.gov/Archives/edgar/data/1083301/000108330126000026/a_wulfearningsrelease2026-.htm','2026-02-26','Abernathy JV 168 MW critical IT; power-controlled platform; subsequent JV sale is not a second site')
source('dc_cipher_sites','Cipher Digital infrastructure ledger','https://cipherdigital.com/infrastructure/',None,'Named campus MW and energization windows. Current Colchis target 2028–29 supersedes earlier 2028. Capacity is site power, not leased critical IT.')
source('dc_cipher_10q','Cipher Q1 2026 Form 10-Q','https://investors.cipherdigital.com/static-files/6e976283-0e50-4f21-ab70-d3c6d5f1275e',None,'Barber Lake and Black Pearl: 300 MW each interconnection approvals; Colchis AEP direct interconnect; Ulysses secured AEP Ohio capacity')
source('dc_fermi','Fermi Q2 2026 investor presentation','https://www.sec.gov/Archives/edgar/data/2071778/000207177826000046/fermi2q2026investorprese.htm',None,'4.8 GW planned generation in ~30 months including Hillcore BOOT; 2.6 GW Hillcore is not unallocated demand')
source('dc_fermi_progress','Fermi physical equipment progress','https://fermiamerica.com/progress/',None,'Secured gas generation equipment; 17 GW private power ambition is generation, not a 2028 tenant load')
source('dc_homer','Homer City / Kiewit / GEV announcement','https://www.gevernova.com/news/press-releases/homer-city-redevelopment-kiewit-announce-country-largest-natural-gas-powered-data-center-support-ai-hpc-demand','2025-04-02','Up to 4.5 GW generation, seven GEV turbines; first turbine deliveries expected 2026. Generation is not leased IT load.')
source('dc_meta_elpaso','Meta El Paso BlackRock venture','https://about.fb.com/news/2026/07/meta-announces-new-venture-with-blackrock-to-develop-data-center-in-el-paso/',None,'1 GW compute capacity; start bringing capacity online 2028. Compute MW definition and phase size not specified.')
source('dc_meta_senate','Senate inquiry on Meta gas power','https://www.epw.senate.gov/public/_cache/files/b/a/ba3b19aa-25f5-48e6-8522-3b8085a597b2/CB05A6BE1D680998DC41351054391E7915B2D726067B9BAE77B8D9D7CC892FF8.letter-to-meta.pdf','2026-03-13','p. 1: proposed gas power at Socrates and El Paso; p. 3 asks equipment choice. Inquiry is not a final permit or supplier award.')
source('dc_meta_lebanon','Meta Lebanon announcement','https://about.fb.com/news/2026/02/metas-new-data-center-lebanon-indiana-marks-milestone-ai-investment/',None,'1 GW campus; groundbreaking. No electrical vs IT distinction or firm energization date in selected text.')
source('dc_meta_tulsa','Meta Tulsa announcement','https://datacenters.atmeta.com/2026/04/hello-tulsa/','2026-04-21','Campus announcement; no site-load MW. 1,500 MW renewable procurement is state-wide, not campus load.')
source('dc_meta_nuclear','Meta nuclear procurement / Prometheus','https://about.fb.com/news/2026/01/meta-nuclear-energy-projects-power-american-ai-leadership/',None,'Power added to supporting grids including Prometheus; 6.6 GW is multi-project generation through 2035, not 2028 site load.')
source('dc_entergy_meta','Entergy Meta infrastructure plan','https://www.entergy.com/news/entergy-louisiana-power-meta-s-data-center-in-richland-parish','2024-12-06','2,260 MW utility generation, not full campus load; target plants 2028–29')
source('dc_entergy_approval','Entergy LPSC infrastructure approval','https://www.entergy.com/news/entergy-louisiana-receives-lpsc-approval-for-major-infrastructure-investments-to-support-metas-data-center-and-improve-reliability','2025-08-20','Two utility plants targeted late 2028. Existing-grid supply ramp not disclosed here.')
source('dc_nc_bridge','NC DEQ final Amazon / Duke bridge permits','https://content.govdelivery.com/accounts/NCDEQ/bulletins/427509e','2026-08-28','57 non-emergency bridge engines, retired within one year of operation; 588 separate emergency engines. Neither count is campus MW.')
source('dc_va2','Virginia DEQ Vantage VA2 assessment','https://www.deq.virginia.gov/home/showpublisheddocument/35701/639128956440930000','2026-04-27','p. 3: eight Solar SMT130, 16.5 MWe each; primary generation operating April 1, 2024. 132 MW is generator rating, not open demand.')
source('dc_pa_aws','Pennsylvania AWS site announcement','https://www.pa.gov/governor/newsroom/2025-press-releases/gov-announces-amazon-to-invest--20b-in-pa--largest-capital-inves','2025-06-09','Named Salem and Falls townships; no campus MW. $20bn is a shared investment announcement.')
source('dc_aws_rainier','Amazon Indiana / Rainier site context','https://www.aboutamazon.com/news/company-news/amazon-15-billion-indiana-data-centers','2025-11-24','Existing New Carlisle; new Northern Indiana campuses add 2.4 GW collectively, not allocated to New Carlisle.')
source('dc_aws_mississippi','Amazon Mississippi expansion','https://www.aboutamazon.com/news/company-news/amazon-25-billion-mississippi-data-centers','2026-05-01','Madison, Warren, Hinds named; no site MW. $25bn statewide is not site-load capacity.')
source('dc_aws_warren','Amazon Warren County campus','https://www.aboutamazon.com/news/company-news/amazon-3-billion-mississippi-data-center-investment',None,'New Warren County campus. No MW or commissioning month.')
source('dc_google_ar','Google West Memphis announcement','https://blog.google/company-news/inside-google/company-announcements/google-american-innovation-arkansas/','2025-10-02','Through-2027 investment; 600 MW is solar procurement, not firm site-load power.')
source('dc_google_mn','Google Pine Island / Xcel agreement','https://blog.google/innovation-and-ai/infrastructure-and-cloud/global-network/data-center-pine-island/','2026-02-24','Xcel supplies power; wind/solar/storage procurement must not be summed into site demand.')
source('dc_google_ok','Google Oklahoma campus ledger','https://www.datacenters.google/locations/oklahoma/',None,'Stillwater and Muskogee announced 2025, Tulsa County 2026; no project MW in selected publisher page')
source('dc_ms_wi','Microsoft Fairwater / Wisconsin expansion','https://blogs.microsoft.com/on-the-issues/2025/09/18/made-in-wisconsin-the-worlds-most-powerful-ai-datacenter/','2025-09-18','First campus early-2026 target, second similar-size campus investment through 2028; no site MW disclosed')
source('dc_ms_laporte','Microsoft La Porte construction update','https://local.microsoft.com/blog/la-porte-public-meeting-recap/',None,'July 2026 update: grading, future vertical build. No MW or power-ready month disclosed.')
source('dc_rowan','Rowan Temple power arrangement','https://rowan.com/rowan-powers-texas-growth-as-construction-begins-on-300-mw-temple-data-center/','2026-01-05','300 MW campus; Oncor power secured; operations expected 2027; MW basis unspecified')
source('dc_nuai_site','New Era TCDC phased power plan','https://www.newerainfra.ai/_resources/First%20Quarter%20FY26%20Business%20Update.pdf?v=052106','2026-05-18','p. 7: 200 MW adjacent generation, 450 MW turbines on order, 750 MW further BTM/grid expansion. No full-campus 2028 guarantee.')
source('dc_nuai_supply','New Era / Thunderhead generation equipment','https://investors.newerainfra.ai/news/news-details/2026/New-Era-Energy--Digital-Announces-450-MW-Behind-the-Meter-Generation-Plan-at-TCDC-with-Thunderhead-Energy-and-TURBINE-X-Energy/default.aspx','2026-02-27','450 MW equipment commercial arrangement; definitive purchase documentation still being finalized at announcement')
source('dc_wi_order','Wisconsin PSC Ozaukee final order','https://psc.wi.gov/Pages/CommissionActions/CasePages/OzaukeeTransmission.aspx','2026-09-10','137-CE-221 completeness revoked; current network cannot support new load. New application possible; no revised customer energization date.')
source('dc_tx_pause','Texas governor permit halt','https://gov.texas.gov/news/post/governor-abbott-directs-tceq-to-halt-data-center-permits','2026-09-21','TCEQ halt until audit information acquired; on-site power still needs permissions. Not a permanent grid-only ban.')
source('dc_ercot_rfi','ERCOT data-center audit RFI','https://www.ercot.com/about/legal/data-center-impact-rfi',None,'25 MW+ developers; October 12 submission deadline; report by December 10, 2026. Queue requests not realized load.')
source('dc_claude_google','Crusoe identifies Google at Claude','https://www.crusoe.ai/resources/newsroom/crusoe-developing-data-center-campus-in-armstrong-county-texas','2026-09-28','Google tenant confirmed; June 2025 groundbreaking; Goodnight wind connections. No turbine order or campus-ready date disclosed.')

rows=[]
def site(id,name,developer,customer,place,state,lat,lon,mw,basis,window,first,last,status,power,stage,refs,**kw):
    rows.append(dict(id=id,name=name,developer=developer,customer=customer,place=place,state=state,lat=lat,lon=lon,mw=mw,basis=basis,readyWindow=window,firstYear=first,lastYear=last,status=status,power=power,stage=stage,sources=refs,confirmedSupplyMw=None,supplyMeaning='Site-specific supply MW not quantified in reviewed material',gridWindow='Customer-load connection date not verified',gas='Firm gas delivery not verified',permit='Primary turbine permit not matched',fit='Not qualified for Mod-1',modelEligible=False,phase2027=0,phase2028=0,bridgeFraction=0,deductMw=0,**{}))
    rows[-1].update(kw)

site('ms_abilene','Microsoft Abilene','Crusoe / Lancium','Microsoft','Abilene','TX',32.45,-99.73,900,'electrical','First building mid-2027',2027,2027,'procurement','Dedicated 900 MW on-site plant; individual OEM allocation unresolved','Site preparation / construction',['crusoe_microsoft','dc_crusoe_report'],modelEligible=True,phase2027=.5,phase2028=.85,bridgeFraction=1,fit='On-site turbine procurement lead; supply allocation and permits unresolved',note='Use 900 MW campus/plant scope. The earlier 672 MW IT figure is the same two-building project, not another demand row.')
site('frontier','Frontier','Vantage','Oracle / OpenAI','Shackelford County','TX',32.73,-99.29,1400,'IT','First customer delivery 1H 2027',2027,2027,'procurement','115 MW available; remaining campus supply allocation unresolved','Development / staged power',['vantage_frontier','oracle_site_update','volta_oracle'],confirmedSupplyMw=115,supplyMeaning='Available power in June 2026; not proof of all design load served',modelEligible=True,phase2027=.35,phase2028=.75,bridgeFraction=1,deductMw=115,fit='Turbine screen; firm gas, emissions permission and competing awards unresolved',note='VoltaGrid 2.3 GW Oracle agreement is multi-site. No wholesale subtraction without a site allocation.')
site('claude','Claude AI campus','Crusoe','Undisclosed hyperscaler','Claude','TX',35.11,-101.36,900,'unspecified','Under construction; no reviewed commissioning date',None,None,'unknown','Dedicated strategy not allocated in selected report','Under construction',['dc_crusoe_report'],note='900 MW campus announcement, electrical/IT definition unresolved. No automatic 2028 gap assignment.')
site('crusoe_childress','Crusoe Childress','Crusoe / Lancium','Undisclosed hyperscaler','Childress','TX',34.43,-100.20,1000,'electrical','Construction starts Q3 2026; service date not disclosed',None,None,'secured','1 GW approved grid interconnect; Lancium develops power infrastructure','Announced / construction target',['dc_crusoe_childress','dc_lancium_childress'],confirmedSupplyMw=1000,supplyMeaning='Approved interconnect capacity, not electricity already delivered',note='Separate from IREN Childress. Construction-start date is not operational date.')
site('abilene_original','Stargate Abilene original','Crusoe / Lancium','Oracle / OpenAI','Abilene','TX',32.48,-99.77,1200,'electrical','Partly operational; phased 2026 buildout',2026,2026,'selected','Grid connection plus GE backup; 42% delivered in June update','Operating / under construction',['crusoe_abilene','oracle_site_update','dc_crusoe_report'],note='Does not include adjacent Microsoft 900 MW expansion. Historical Longhorn turbines not added again.')
site('lighthouse','Lighthouse','Vantage','Oracle / OpenAI','Port Washington','WI',43.39,-87.88,902,'IT','First customer 2H 2027; campus completion 2028',2027,2028,'timing','We Energies arranged supply; ATC transmission review completeness revoked Sept 10','Under construction',['vantage_lighthouse','oracle_site_update','dc_wi_order'],modelEligible=True,phase2027=.25,phase2028=.65,bridgeFraction=.25,gridWindow='Revised connection date unverified after PSC order',fit='Transmission-risk watch; no approved Mod-1 bridge plan',note='25% bridge fraction is our stress assumption. A regional transmission delay does not mean the entire campus is open turbine demand.')
site('saline','Saline / Green Chile','Related Digital','Oracle / OpenAI','Saline Township','MI',42.15,-83.78,1400,'electrical','Load ramp 2027; first customer 2H 2027',2027,2027,'timing','DTE utility contracts conditionally approved; actual monthly matching unresolved','Under construction',['saline_dte','saline_brief','oracle_site_update'],modelEligible=True,phase2027=.5,phase2028=1,bridgeFraction=.1,gridWindow='End-2027 maximum-load target; utility ramp not independently matched',fit='Timing watch, not a proven 1.4 GW shortage',note='10% bridge fraction is our stress assumption. Capacity ramp and supply ramp must be compared month by month.')
site('jupiter','Project Jupiter','BorderPlex','Oracle / OpenAI','Doña Ana County','NM',31.82,-106.58,None,'unknown','First customer 1H 2027',2027,2027,'selected','Bloom fuel-cell microgrid selected, superseding turbine/diesel design','Under construction',['oracle_jupiter','oracle_site_update'],fit='Current selected technology is fuel cells',note='No campus MW from reviewed primary material. Excluded from normalized capacity and open turbine pool.')
site('milam','Milam data center','SB Energy','OpenAI / Stargate','Milam County','TX',30.85,-96.98,None,'unknown','Construction; first date unresolved in selected primary page',None,None,'unknown','Power strategy not reconciled at facility level','Under construction',['dc_sb_milam'],note='1+ GW headline scope not reconciled to current filings; no numeric assignment until capacity basis and phased supply verified.')
site('cheyenne','Cheyenne 1.8 GW campus','Tallgrass / Black Hills','Prospective customer','Cheyenne','WY',41.14,-104.82,1800,'electrical','Utility service expected early 2028',2028,2028,'selected','Utility tariff plus customer long-lead generation procurement agreement','Development',['dc_cheyenne'],note='Crusoe left project. An equipment procurement agreement is not an unallocated 1.8 GW modular order.')
site('iren_sw1','Sweetwater 1','IREN','AI cloud / future tenants','Sweetwater','TX',32.47,-100.41,1400,'electrical','Earlier energization target April 2026; current delivery phases unresolved',2026,2028,'secured','Grid-connected power secured; AI buildout is separately phased','Development / commissioning',['dc_iren_annual','dc_iren_may','dc_iren_fy26'],confirmedSupplyMw=1400,supplyMeaning='Secured grid capacity; not full operational IT load',note='Do not add 2 GW Sweetwater parent campus to SW1 plus SW2.')
site('iren_sw2','Sweetwater 2','IREN','AI cloud / future tenants','Sweetwater','TX',32.45,-100.36,600,'electrical','Historical grid target late 2027',2027,2027,'secured','Grid-connected capacity; historical target needs refresh','Development',['dc_iren_annual','dc_iren_may','dc_iren_fy26'],confirmedSupplyMw=600,supplyMeaning='Secured capacity, not commissioned IT load',note='A future grid date without an earlier tenant-ready date does not establish a bridge gap.')
site('iren_childress','IREN Childress / Horizons','IREN','Microsoft / AI cloud','Childress','TX',34.46,-100.23,750,'electrical','Horizon 1 delivered; 2–4 target Q4 2026',2026,2026,'secured','Existing grid-connected campus, unused power headroom','Operating / AI conversion',['dc_iren_annual','dc_iren_fy26'],confirmedSupplyMw=750,supplyMeaning='Campus secured electrical capacity; not all operating AI capacity',note='Mining conversion, not all incremental electricity demand. Separate from Crusoe/Lancium Childress.')
site('kiowa','Kiowa','IREN','Future AI customers','Kiowa','OK',34.72,-95.90,1600,'electrical','Power scheduled to ramp from 2028',2028,2028,'secured','Grid studies complete, secured grid-connected power','Development',['dc_iren_q2','dc_iren_fy26'],confirmedSupplyMw=1600,supplyMeaning='Secured grid capacity with future ramp',note='No independently earlier customer-ready date; no verified pre-grid shortage.')
site('river_bend','River Bend','Hut 8','Fluidstack / Anthropic','St. Francisville','LA',30.78,-91.38,245,'IT','Initial halls Q2 2027',2027,2027,'secured','330 MW utility capacity; substation and long-lead equipment construction','Under construction',['dc_hut_q2'],confirmedSupplyMw=330,supplyMeaning='Utility capacity supporting leased 245 MW IT',note='Potential additional 1 GW is not booked phase-one load.')
site('beacon','Beacon Point','Hut 8','High-investment-grade tenant, unnamed','Nueces County','TX',27.73,-97.45,704,'IT','Initial energization Q1 2027, halls Q3 2027; phase 2 later',2027,2028,'secured','1,000 MW utility capacity under construction','Under construction',['dc_hut_q2'],confirmedSupplyMw=1000,supplyMeaning='Two 500 MW utility phases, not energized today',note='Two 352 MW leases counted once as 704 MW IT; date does not guarantee full phase 2 by 2028.')
site('pf1','Polaris Forge 1','Applied Digital','CoreWeave','Ellendale','ND',46.00,-98.52,400,'IT','100 MW operating, next 150 in 2026 and 150 in 2027',2026,2027,'secured','Grid-fed campus; initial building operating','Operating / construction',['dc_apld_q3'],note='Exclude separate 180 MW legacy crypto facility from AI lease capacity.')
site('pf2','Polaris Forge 2','Applied Digital','Investment-grade hyperscaler, unnamed','Harwood','ND',46.98,-96.88,200,'IT','Initial 2026, full contracted phase early 2027',2026,2027,'secured','Grid-connected utility power; critical-IT leases','Under construction',['dc_apld_q3'],note='Earlier 280 MW campus headline and later 200 MW IT contract have different bases; not additive.')
site('df1','Delta Forge 1','Applied Digital','Investment-grade hyperscaler, unnamed','Central Louisiana','LA',31.3,-92.4,300,'IT','Initial mid-2027',2027,2028,'secured','430 MW grid power scope; IT contract is 300 MW','Under construction',['dc_apld_q3','dc_apld_df2'],confirmedSupplyMw=430,supplyMeaning='Campus electrical design scope, not observed delivered power',note='Central-Louisiana marker approximate; first service is not all 300 MW at once.')
site('df2','Delta Forge 2','Applied Digital','Investment-grade hyperscaler, unnamed','Undisclosed southern state','US',None,None,210,'IT','Initial operations Q1 2028',2028,2028,'secured','Part of disclosed grid-connected utility portfolio; site MW allocation unextracted','Leased / development',['dc_apld_df2'],note='Location withheld by publisher; retained in census but omitted from geographic map. No fabricated coordinates.')
site('lake_mariner','Lake Mariner','TeraWulf','Fluidstack / Google credit support','Somerset','NY',43.36,-78.60,438,'IT','102 MW operating July 2026; 336 under construction to 1H 2027',2026,2027,'secured','Power-controlled brownfield; existing transmission','Operating / construction',['dc_wulf_q2'],note='250 MW additional interconnect application is future optionality, not added to leased 438 MW.')
site('justified','Justified / Hawesville','TeraWulf','Anthropic','Hawesville','KY',37.90,-86.75,401,'IT','Initial 2H 2027, full early 2028',2027,2028,'secured','Power-backed former industrial site; lease does not establish open turbine procurement','Leased / development',['dc_wulf_q2'],note='Use latest 401 MW lease, not older 384 MW design. Own gas or permits unresolved in this review.')
site('muskie','Muskie','TeraWulf','Future tenants','Grayson','KY',38.33,-82.94,1000,'electrical','Initial utility service Q4 2028; phases thereafter',2028,2029,'secured','Up to 1 GW contracted Kentucky Power electric service','Acquired / development',['dc_wulf_q2'],confirmedSupplyMw=1000,supplyMeaning='Contracted future utility service, not online electricity',note='1 GW electric service is not equivalent to 1 GW critical IT by 2028.')
site('hawkeye','Lake Hawkeye','TeraWulf','Future tenants','New York industrial site','NY',43.05,-76.15,400,'electrical','Operations not contemplated until approximately 2029',2029,2029,'later','Former industrial electrical infrastructure; permits and development pending','Early redevelopment',['dc_wulf_q2'],note='Approximate regional marker, not surveyed parcel. Excluded from 2028 opportunity scenarios.')
site('chesapeake','Chesapeake / Morgantown','TeraWulf','Future tenants','Morgantown','MD',38.35,-76.95,1000,'electrical','Initial data-center operations contemplated 2030',2030,2030,'later','Existing generation site; acquisition / approvals conditional','Conditional acquisition',['dc_wulf_q2'],note='210 MW operating generation is not commissioned data-center IT; 2030 outside our horizon.')
site('abernathy','Abernathy JV campus','TeraWulf / Fluidstack','Fluidstack','Abernathy','TX',33.83,-101.84,168,'IT','Phased 2026/27 development; subsequent ownership sale','2026','2027','secured','Power-controlled campus; no independently uncovered load','Development',['dc_wulf_abernathy','dc_wulf_q2'],note='JV sale changes ownership, not a second campus. Site allocation must survive sale before attribution.')
site('barber','Barber Lake','Cipher','Fluidstack / Google credit support','West Texas','TX',31.8,-102.8,300,'electrical','Publisher currently lists energized; filed phase II Jan 2027 target',2026,2027,'secured','300 MW interconnection approved without load-profile restrictions','Energized / phased buildout',['dc_cipher_sites','dc_cipher_10q'],confirmedSupplyMw=300,supplyMeaning='Interconnect approval; current website labels energized, tenant acceptance distinct',note='Approximate regional marker. No 300 MW uncontracted shortage from a financed grid project.')
site('black_pearl','Black Pearl','Cipher','AWS','Wink','TX',31.75,-103.15,300,'electrical','Publisher currently lists energized; earlier phase ramp Q4 2026–Q1 2027',2026,2027,'secured','300 MW approved interconnection; conversion from crypto','Energized / retrofit',['dc_cipher_sites','dc_cipher_10q'],confirmedSupplyMw=300,supplyMeaning='Approved power; website energized label not all tenant IT accepted',note='AWS tenant lease is compute procurement, not evidence of a new turbine order.')
site('colchis','Colchis','Cipher','Future hyperscale tenant','West Texas','TX',31.9,-102.5,1000,'electrical','Current target 2028–29; earlier filing targeted 2028',2028,2029,'secured','Executed AEP direct interconnection agreement','Development',['dc_cipher_sites','dc_cipher_10q'],confirmedSupplyMw=1000,supplyMeaning='Direct interconnect contract, date still estimated',note='Do not treat full capacity as available or short in 2028; window straddles horizon.')
site('ulysses','Ulysses','Cipher','Future hyperscale tenant','Ohio','OH',40.3,-82.5,200,'electrical','Energization target Q4 2027',2027,2027,'secured','AEP Ohio capacity secured','Development',['dc_cipher_sites','dc_cipher_10q'],confirmedSupplyMw=200,supplyMeaning='Acquired utility capacity; not current energized IT',note='Exact site location withheld here; marker is approximate region.')
site('reveille','Reveille','Cipher','Future customer','Texas','TX',31.4,-100.5,70,'electrical','Q3 2027 energization target',2027,2027,'secured','Publisher power-development ledger; no earlier tenant-ready date','Pipeline',['dc_cipher_sites'],note='Exact location unresolved; approximate regional marker. Not a verified power shortage.')
site('fermi','Project Matador','Fermi America','Tenant commitments evolving','Amarillo / Carson County','TX',35.35,-101.7,17000,'generation','Multi-decade private power ambition; early phases 2026–28',2026,2038,'selected','Siemens / reused GE equipment plus Hillcore BOOT; gas and permits announced','Physical equipment / construction',['dc_fermi','dc_fermi_progress'],permit='Initial 6 GW gas permission company-reported; extra capacity not fully permitted',gas='Company reports secured gas; entire planned 17 GW not independently reconciled',note='17 GW is generation ambition, not 2028 tenant demand. Do not subtract combined-cycle ratings from simple-cycle bridge load.')
site('homer','Homer City','HCR / Kiewit','Future AI/HPC tenants','Homer City','PA',40.54,-79.15,4500,'generation','First turbine deliveries 2026; complete site-ready date not established',2026,2028,'selected','Seven GE Vernova turbines selected for up to 4.5 GW plant','Redevelopment',['dc_homer'],note='Shows real competition with booked turbines, not 4.5 GW open FTAI load.')
site('meta_hyperion','Hyperion','Meta / Blue Owl','Meta','Richland Parish','LA',32.46,-91.75,None,'unknown','Phased campus; two new utility plants late 2028',2027,2029,'secured','Entergy approved generation and transmission; grid service ramp unextracted','Under construction',['dc_entergy_meta','dc_entergy_approval'],note='2,260 MW new utility generation is not site load. Ultimate 5 GW headlines cannot be treated as uncovered 2028 demand.')
site('meta_elpaso','Meta El Paso','Meta / BlackRock','Meta','El Paso','TX',31.85,-106.3,1000,'unspecified','Begin bringing capacity online 2028',2028,2028,'unknown','Gas plans referenced in Senate inquiry; final equipment allocation unverified','Under construction',['dc_meta_elpaso','dc_meta_senate'],note='Compute-capacity MW basis unresolved, gas inquiry not final equipment award. Excluded from normalized demand until reviewed.')
site('meta_lebanon','Meta Lebanon','Meta','Meta','Lebanon','IN',40.05,-86.47,1000,'unspecified','Groundbreaking 2026; selected primary source gives no first-power date',None,None,'unknown','Utility and on-site allocations not reconciled in reviewed announcement','Groundbreaking',['dc_meta_lebanon'],note='Campus MW definition unclear. No guessed 2028 ready date or open supply.')
site('meta_prometheus','Prometheus / New Albany','Meta','Meta','New Albany','OH',40.08,-82.81,None,'unknown','Supporting-grid nuclear agreements, different maturities','2026','2035','secured','Existing nuclear PPAs plus future projects; site-specific ramp unresolved','Campus expansion',['dc_meta_nuclear','dc_meta_senate'],note='Socrates gas inquiry may overlap campus projects; not added as a separate 400 MW site without identity reconciliation.')
site('meta_tulsa','Meta Tulsa','Meta','Meta','Tulsa','OK',36.15,-95.99,None,'unknown','Announced April 2026; opening date unresolved',None,None,'unknown','PSO collaboration; state-wide renewable commitments not firm site capacity','Announced',['dc_meta_tulsa'],note='No conversion of $1bn investment or renewable MW into campus load.')
site('aws_richmond','Energy Way Tech Campus','AWS','AWS','Hamlet / Richmond County','NC',34.88,-79.70,None,'unknown','Approved bridge engines; one-year maximum operation before retirement',None,None,'selected','Duke 57 non-emergency bridge engines; AWS 588 emergency engines separate','Construction / final air permits',['dc_nc_bridge'],permit='Final permits issued August 28, 2026',fit='Bridge need directly evidenced, but equipment selected is diesel',note='Strong demand-mechanism evidence. No MW extrapolated from 57 engines; no open Mod-1 award.')
site('aws_salem','AWS Salem / Susquehanna','AWS','AWS','Salem Township','PA',41.08,-76.15,None,'unknown','2025 expansion announcement; precise phase dates not extracted',None,None,'unknown','Nuclear adjacency; service structure not fully reconciled in this review','Existing campus / expansion',['dc_pa_aws'],note='Not all statewide $20bn allocated here. No capacity from spend.')
site('aws_falls','AWS Falls Township','AWS','AWS','Falls Township','PA',40.18,-74.82,None,'unknown','2025 campus announcement; utility-ready month unverified',None,None,'unknown','Power allocation unextracted; 600 MW secondary claim not used as measured fact','Announced / development',['dc_pa_aws'],note='No unverified 600 MW in headline totals; site confirmed, MW open.')
site('aws_carlisle','AWS New Carlisle / Rainier','AWS','AWS / Anthropic compute','New Carlisle','IN',41.70,-86.51,None,'unknown','Existing campus; Rainier context, incremental phase dates unextracted',2025,2028,'secured','Existing Indiana data-center infrastructure','Operating / expansion',['dc_aws_rainier'],note='New 2.4 GW Northern Indiana program cannot be assigned to this existing site or counted as a second named campus.')
site('aws_madison','AWS Madison County campuses','AWS','AWS','Canton / Madison County','MS',32.60,-90.03,None,'unknown','Construction and expansion; phase dates unextracted',None,None,'unknown','Entergy grid investments; per-campus supply not reconciled','Construction / expansion',['dc_aws_mississippi'],note='Two separately mentioned campuses grouped as one program record because site allocations unextracted. No inflated site count.')
site('aws_warren','AWS Warren County','AWS','AWS','Vicksburg / Warren County','MS',32.35,-90.88,None,'unknown','Announced; phase dates not disclosed in selected source',None,None,'unknown','Power contracts unextracted','Announced',['dc_aws_warren','dc_aws_mississippi'],note='Distinct county program; no dollar-to-MW inference.')
site('aws_hinds','AWS Hinds County Delphi conversion','AWS','AWS','Clinton / Hinds County','MS',32.34,-90.32,None,'unknown','Manufacturing-site conversion announced 2026',None,None,'unknown','Utility supply unextracted','Announced / conversion',['dc_aws_mississippi'],note='Separate from Madison and Warren; $1bn is capex, not MW.')
site('google_ar','Google West Memphis','Google','Google','West Memphis','AR',35.15,-90.18,None,'unknown','Investment through 2027; exact operational date unverified',None,None,'secured','Entergy grid supply; solar supports portfolio, not sole firm capacity','Announced / construction',['dc_google_ar'],note='600 MW solar not campus electric load or a 600 MW grid shortage.')
site('google_mn','Google Pine Island','Google','Google','Pine Island','MN',44.2,-92.65,None,'unknown','Announced February 2026; first-power date unextracted',None,None,'secured','Xcel service agreement; CEAC clean-energy additions','Announced',['dc_google_mn'],note='Wind, solar and storage nameplates not added into load or firm gas market.')
site('google_muskogee','Google Muskogee County','Google','Google','Muskogee County','OK',35.75,-95.37,None,'unknown','New campus announced 2025',None,None,'unknown','Site supply not quantified in publisher ledger','Development',['dc_google_ok'],note='Separate from unrelated Polaris crypto campus in Muskogee; no false 200 MW name join.')
site('google_stillwater','Google Stillwater','Google','Google','Stillwater','OK',36.12,-97.06,None,'unknown','New campus announced 2025',None,None,'unknown','Site supply unextracted','Development',['dc_google_ok'],note='MW not disclosed in selected primary source.')
site('ms_wisconsin','Microsoft Fairwater / expansion','Microsoft','Microsoft','Mount Pleasant','WI',42.72,-87.89,None,'unknown','Original target early 2026; next similar campus investment through 2028',2026,2028,'secured','Utility supply and operating phases; specific MW allocation unextracted','Operating target / expansion',['dc_ms_wi'],note='Grouped campuses to avoid claiming two site loads from one investment announcement.')
site('ms_laporte','Microsoft La Porte','Microsoft','Microsoft','La Porte','IN',41.61,-86.72,None,'unknown','Grading July 2026; future vertical build; first-power date unknown',None,None,'unknown','Site electric-load schedule unextracted','Grading',['dc_ms_laporte'],note='Construction evidence, not an energization shortage estimate.')
site('rowan_temple','Rowan Temple','Rowan','Global technology company, unnamed','Temple','TX',31.10,-97.34,300,'unspecified','Operations expected 2027',2027,2027,'secured','Oncor power secured','Under construction',['dc_rowan'],note='300 MW basis unspecified; excluded from standardized electric-load subtotal.')
site('tcdc','Texas Critical Data Centers','New Era','Anchor tenant not identified','Ector County','TX',31.85,-102.45,1400,'electrical','Phased development; full buildout date unresolved','2027','2029','selected','200 MW adjacent-power path; 450 MW turbine procurement; 750 MW future expansion','Development',['dc_nuai_site','dc_nuai_supply'],note='1.4 GW phased power pathway. Initial suppliers selected; 750 MW later expansion not verified ready or open by 2028.')
site('va2_control','Vantage VA2 operating control','Vantage','Colocation tenants','Sterling','VA',38.99,-77.43,132,'generation','Primary gas turbines operating since April 2024',2024,2024,'selected','8 Solar SMT130 × 16.5 MWe; already supplying primary power','Operating',['dc_va2'],confirmedSupplyMw=132,supplyMeaning='Installed generator nameplate, not IT or open MW',permit='Virginia facility 74242; September 2023 NSR; April 2026 assessment',gas='Operating natural-gas turbine facility',fit='Real modular gas precedent; existing competitor equipment',note='Historical control, not a new 2027/28 announcement or opportunity.')
# The SB Energy page is an official announcement, retained with unknown site MW.
source('dc_sb_milam','SB Energy digital infrastructure','https://sbenergy.com/digital-infrastructure/',None,'Milam data center; multi-gigawatt portfolio / aspirational capacity not assigned to a single near-term site')
claude=next(r for r in rows if r['id']=='claude')
claude.update(customer='Google',sources=claude['sources']+['dc_claude_google'],power='Direct wind connections confirmed; firm gas and grid allocation not reconciled',note='Latest September 28 release confirms Google. 900 MW campus basis and service date unresolved; wind nameplates are not firm capacity.')
# Keep 50 main records; preserve four secondary/out-of-horizon leads in a separate audit.
supplemental=[r for r in rows if r['id'] in ['hawkeye','chesapeake','reveille','meta_prometheus']]
rows=[r for r in rows if r not in supplemental]
for r in rows:
    for key in ['firstYear','lastYear']:
        if isinstance(r[key],str):r[key]=int(r[key])
    r['coordinateBasis']='Approximate city / regional marker; not a surveyed facility footprint' if r['lat'] is not None else 'Undisclosed location; omitted from map'
    r['reviewed']='2026-10-06'
    r['durationMonths']=None
    r['verifiedOpenMw']=None
    if r['state']=='TX':r['regulatoryNote']='September 21 TCEQ pause: site-specific permit status and audit completion must be checked.'
    else:r['regulatoryNote']='No generic permission assumed; emissions, fuel and customer acceptance are site-specific.'
used={sid for r in rows for sid in r['sources']}|{'dc_tx_pause','dc_ercot_rfi','gev_capacity','siemens_slots','wartsila_slots','wartsila_282','volta_oracle','gev_crusoe_units','ftai_q2'}
missing=used-sources.keys()
assert not missing,missing
out=dict(asOf='2026-10-06',scope='50 US named-campus and campus-program records, including an operating turbine control. Purposive coverage of major hyperscalers and AI developers; not an exhaustive global registry or a statistical meta-analysis.',rows=rows,supplemental=supplemental,sources=[sources[id] for id in sorted(used)],defaults=dict(year=2028,pue=1.2,competitorShare=.5,capture=.25,phaseScale=1,includeTiming=True,derate=.1,reserve=.1,annualUnits=100),limitations=['Announcements and utility contracts are guidance, not commissioned load.','Only IT and explicitly electrical capacity enter normalized demand; generation and unspecified MW stay separate.','Modeling undisclosed supplier allocation as a potential procurement pool does not prove an open tender.','No independent execution-qualified open MW or shortage duration established.','Default 2028 phase and bridge fractions are team assumptions and editable; a service-ready date is not assigned to unknown cases.'],previous=dict(openMw=564.1,sites=2,scope='2027 two-site model; 50% load phase and 50% remaining competing supply. Different cohort, basis and horizon from this census.'))
(R/'data/datacenter_study.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print(f'Curated {len(rows)} campus/program records and {len(out["sources"])} sources.')
