import {useState,type ReactNode} from 'react';
import {ArrowRight,Copy,Check,Download,Search,ExternalLink} from 'lucide-react';
import audit from '../data/power_gap_audit.json';
import sourceIndex from '../data/power_gap_source_index.json';
import {Plot} from './Plot';
import './power-audit.css';
export const powerAuditSummary=audit.summary;
type Row=typeof audit.rows[number];
const base=import.meta.env.BASE_URL,num=(v:number,dp=0)=>v.toLocaleString('en-US',{maximumFractionDigits:dp}),gw=(v:number)=>`${num(v/1000,2)} GW`;
const erock='https://www.sec.gov/Archives/edgar/data/2110029/000119312526265898/d12401d424b4.htm';
const categories=[['Load MW missing','16','No usable customer-load MW'],['Capacity definition unresolved','6','MW basis or full scope unclear'],['No reviewed first-service window by 2028','1','Service window unverified'],['Generation scope, not customer load','3','Generation / historical control']];
function File({name,children}:{name:string;children:ReactNode}){return <a className="w-action" href={`${base}data/${name}`} download><Download size={15}/>{children}</a>}
function Panel({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){return <section className="w-panel pa-panel"><div className="w-eyebrow">{eyebrow}</div><h2>{title}</h2>{children}</section>}
function group(r:Row){return !r.boundIncluded?'excluded':(r.contractCoverageCeilingMw??0)>0?'unmatched':'credited'}
const names={excluded:'Outside numerical bound',unmatched:'Supply volume unresolved',credited:'Numeric credit covers stated scope'},colors={excluded:'#a5b0b7',unmatched:'#c59650',credited:'#457764'};
const sources=sourceIndex as Record<string,{title:string;published:string|null;locator:string;reviewed:string}>;
function Sources({row}:{row:Row}){return <div className="pa-source-list">{[...new Set(row.sourceUrls)].map(url=>{const s=sources[url];return <a href={url} target="_blank" rel="noreferrer" key={url}><b>{s?.title??new URL(url).hostname} <ExternalLink size={12}/></b><small>{s?.locator} · Published {s?.published??'date unverified'} · Reviewed {s?.reviewed??audit.asOf}</small></a>;})}</div>}
export function PowerGapAudit(){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState('ms_abilene'),[copied,setCopied]=useState(false);
 const summary=audit.summary,rows=audit.rows,positive=rows.filter(r=>group(r)==='unmatched').sort((a,b)=>b.contractCoverageCeilingMw!-a.contractCoverageCeilingMw!),focus=rows.find(r=>r.id===selected)!;
 const shown=rows.filter(r=>(filter==='all'||group(r)===filter)&&`${r.name} ${r.customer} ${r.place} ${r.state}`.toLowerCase().includes(query.toLowerCase()));
 const pick=(id:string)=>{setSelected(id);document.getElementById('pa-detail')?.scrollIntoView({behavior:'smooth',block:'start'});};
 const finding=`Customers already purchase power to bridge grid delays: ERock's SEC filing identifies 366 MW of multi-year bridge power for Meta/El Paso Electric, already supplier-selected. Our 50-record audit gives a conditional 0–9.2 GW contract-coverage range for 24 measurable records; 26 are held out. The ceiling reflects unmatched public supply volumes, not confirmed uncontracted demand. FTAI can compete where its delivery timing gets customers powered earlier.`;
 return <div className="power-audit"><section className="pa-answer"><div className="w-eyebrow">THESIS 2 · NEW CONTRACT AUDIT · WEBSITE UPDATED OCTOBER 7, 2026</div><h2>The opportunity is earlier electricity.</h2><p className="pa-lead">Customers already buy power to bridge grid delays. Our audit flags a much wider set of projects for supply verification; Mod-1 matters where its delivery date gets a customer powered sooner.</p><div className="pa-headline"><div><span>Conditional contract-coverage range</span><strong>0–{num(summary.conditionalAllocationCeilingMw/1000,1)} GW</strong><b>For 24 measurable records, not all 50</b></div><p><b>What this means:</b> {gw(summary.conditionalAllocationCeilingMw)} is the ceiling for capacity we could not fully match to quantified public supply arrangements. Some may already be covered by undisclosed contracts. A positive uncontracted minimum remains unverified.</p></div><div className="pa-scope"><span><b>50</b> records audited</span><span><b>24</b> enter the arithmetic</span><span><b>26</b> held out, reasons below</span></div><div className="pa-actions"><button className="w-action" onClick={async()=>{try{await navigator.clipboard.writeText(finding);setCopied(true);}catch{setCopied(false);}setTimeout(()=>setCopied(false),2000);}}>{copied?<Check size={15}/>:<Copy size={15}/>}Copy thesis connection</button><File name="power_gap_audit.csv">50-record audit CSV</File><File name="power_gap_audit_memo.md">Research memo</File><a className="w-action" href="#pa-exclusions">See every exclusion <ArrowRight size={15}/></a></div></section>
 <Panel eyebrow="THE ARITHMETIC · NO MARKET-SHARE DEDUCTIONS" title="18.56 GW of scope. 9.38 GW credited. 9.18 GW unresolved."><figure className="pa-figure"><img src={`${base}graphics/power-gap-audit.svg`} alt="50-record audit: 24 measurable records contain 18.56 GW electrical scope, 9.379 GW numeric supply and operating credits, and a conditional 9.181 GW ceiling. 366 MW bridge purchase supports the customer mechanism."/><figcaption>Evidence cutoff October 6. IT load is converted at an assumed 1.2 power usage effectiveness where gross electricity scope is unavailable. Published scope is used where 2028 phases are undisclosed.</figcaption></figure><div className="pa-actions"><a className="w-action" href={`${base}graphics/power-gap-audit.png`} download><Download size={15}/>Download slide image · PNG</a><a className="w-action" href={`${base}graphics/power-gap-audit.svg`} download><Download size={15}/>SVG image</a><File name="power_gap_bridge.csv">Chart arithmetic CSV</File></div><div className="pa-reading"><p><b>The ceiling is wide on purpose.</b> It allows unmatched volumes to remain potentially uncovered rather than assuming a utility strategy supplies the whole campus. It uses full announced scope when phase size is missing.</p><p><b>The zero floor is an evidence limit.</b> Private contracts could cover the remainder. It does not demonstrate zero customer need. The complete 50-record upper bound remains unavailable because missing inputs are not zero.</p><p><b>Contracts and timing are separate.</b> Credited supply includes future capacity rights and minimum operating evidence. It is not unconditional electricity available on a particular date; shortage durations remain unquantified.</p></div><details className="pa-method"><summary>Assumptions, sensitivity and what changed from the old 1–2 GW estimates</summary><p>The earlier model used four campuses, buildout assumptions, a competing-supply haircut and FTAI capture. The new audit uses 24 records with usable scope and a service window beginning by 2028. No assumed competition, FTAI capture or phase haircut enters this calculation. The ceiling change is a method change, not observed growth in shortages.</p><table><thead><tr><th>Assumed IT overhead factor (PUE)</th><th>Conditional ceiling</th></tr></thead><tbody>{audit.pueSensitivities.map(s=><tr key={s.pue}><td>{s.pue}</td><td>{gw(s.conditionalAllocationCeilingMw)}</td></tr>)}</tbody></table><p>These are alternative ceilings, not an 8.74–10.06 GW positive shortage interval. The floor remains zero. Connection agreements and approvals are not firm-hour energy guarantees. Full buildout may occur after first service.</p><File name="power_gap_audit.json">Complete audit JSON</File><File name="gap_audit_acquisition.json">Acquisition successes & failures</File></details></Panel>
 <Panel eyebrow="THE CUSTOMER PROOF · PURCHASED BRIDGE POWER" title="Meta's grid wait led to a 366 MW purchase."><div className="pa-proof"><div><strong>366 MW</strong><span>Purchased bridge generation</span><small>Already supplier-selected</small></div><div><p>Enchanted Rock's SEC filing describes a signed generator purchase for Meta / El Paso Electric and multiple years of bridge use while a substation is built, with initial operation targeted for mid-2027. This is customer demand expressed in a purchase, rather than a headline campus announcement.</p><p><b>Why this supports the long:</b> earlier electricity is already a product customers buy. FTAI's opportunity is to offer it where customer schedules outrun supply and competing delivery dates.</p><a href={erock} target="_blank" rel="noreferrer">ERock SEC prospectus · June 9, 2026 · p. 146 ↗</a><p className="pa-caption">Counted once despite two case-study descriptions in the filing. Not an open FTAI award; approval and commissioning risks remain. AWS's 57 permitted Duke bridge engines provide a second example, but their unverified MW are not added here.</p></div></div></Panel>
 <Panel eyebrow="WHAT BUILDS THE CEILING · 12 RECORDS" title="Where the numerical supply match is still incomplete."><p>Several of these projects already have a selected utility or equipment partner. The bars show the largest remainder allowed by the audit—not twelve proven open tenders. Click a bar for its sources.</p><Plot title="Conditional contract-coverage ceiling by campus" height={480} onPointClick={pick} data={[{type:'bar',orientation:'h',x:[...positive].reverse().map(r=>r.contractCoverageCeilingMw),y:[...positive].reverse().map(r=>r.name),customdata:[...positive].reverse().map(r=>r.id),marker:{color:'#c59650'},text:[...positive].reverse().map(r=>`${num(r.contractCoverageCeilingMw!,1)} MW`),textposition:'outside',cliponaxis:false,hovertemplate:'%{y}<br>%{x:,.1f} MW conditional ceiling<extra>Not a verified shortage</extra>'}]} x="Electrical MW · unmatched numeric allocation" extra={{margin:{l:180,r:110,t:15,b:65},showlegend:false}}/><File name="power_gap_ceiling_cases.csv">12-case chart data</File><div id="pa-detail" className="pa-detail"><span className="pa-tag" style={{color:colors[group(focus)]}}>{names[group(focus)]}</span><h3>{focus.name}</h3><small>{focus.customer} · {focus.place}, {focus.state}</small><p>{focus.auditNote}</p><div className="pa-detail-numbers"><div><span>Electrical scope used</span><b>{focus.boundIncluded?`${num(focus.electricalScopeMwAtPue12!,1)} MW`:'Outside calculation'}</b></div><div><span>Numeric supply credit</span><b>{focus.creditedSupplyMw>0?`${num(focus.creditedSupplyMw)} MW`:'Not quantified'}</b></div><div><span>Conditional ceiling</span><b>{focus.contractCoverageCeilingMw===null?'Unavailable':`${num(focus.contractCoverageCeilingMw,1)} MW`}</b></div></div><p className="pa-caption">{focus.creditType}. {focus.readyWindow}. Actual shortage duration and firm on-time supply remain unverified.</p><Sources row={focus}/></div></Panel>
 <Panel eyebrow="COVERAGE · ALL 50 ACCOUNTED FOR" title="24 enter the number. Here are the other 26."><div id="pa-exclusions" className="pa-exclusions">{categories.map(([reason,count,label])=><details key={reason}><summary><b>{count}</b><span>{label}</span></summary><p>{rows.filter(r=>r.boundInclusionReason===reason).map(r=>r.name).join('; ')}.</p>{rows.filter(r=>r.boundInclusionReason===reason).map(r=><button className="pa-site-link" key={r.id} onClick={()=>pick(r.id)}>{r.name} <ArrowRight size={13}/></button>)}</details>)}</div><p><b>Unknown is left unknown.</b> Missing load or unclear capacity definitions stay outside the arithmetic. That is why 9.2 GW is not an upper limit for the entire 50-record sample.</p><details className="pa-method"><summary>What the previous screen left out: 46 records, including 13 explicitly unresolved</summary><p>The old four-case model excluded 25 utility-strategy records, eight selected-solution records and 13 explicitly unresolved records. It did not establish that all their power needs were met.</p><p><b>The 13:</b> Claude; Milam; Meta El Paso, Lebanon and Tulsa; AWS Salem, Falls, Madison, Warren and Hinds; Google Muskogee and Stillwater; Microsoft La Porte.</p><p>Milam now has ~750 MW published but still lacks a clear electrical-versus-IT definition. Microsoft Abilene uses 672 MW IT rather than its 900 MW plant rating. Justified has a verified 482 MW service agreement. Muskie's second 500 MW is a 2029 phase.</p></details><File name="power_gap_coverage.csv">Exclusion counts CSV</File></Panel>
 <Panel eyebrow="SOURCE LEDGER · CURRENT AUDIT" title="Find any campus and see exactly how it was treated."><div className="pa-filters"><label><Search size={16}/><input aria-label="Search audited campuses" placeholder="Search campus, customer or state" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter audit treatment" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All 50 records</option><option value="unmatched">12 with positive ceilings</option><option value="credited">12 covered by numeric credits</option><option value="excluded">26 outside the bound</option></select></div><p className="pa-caption">{shown.length} of 50 records shown. “Not quantified” means no usable numeric credit was found; it does not mean the customer has no contract.</p><div className="table-scroll"><table className="pa-table"><thead><tr><th>Campus / customer</th><th>Electric scope used</th><th>Supply credited</th><th>Ceiling / exclusion</th><th>Finding</th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td><button onClick={()=>pick(r.id)}>{r.name} ↗</button><small>{r.customer}<br/>{r.place}, {r.state}</small></td><td>{r.boundIncluded?`${num(r.electricalScopeMwAtPue12!,1)} MW`:'Not included'}<small>{r.mw===null?'Published MW unavailable':`${num(r.mw)} MW · ${r.basis} published scope`}</small></td><td>{r.creditedSupplyMw>0?`${num(r.creditedSupplyMw)} MW`:'Not quantified'}<small>{r.creditType}</small></td><td>{r.contractCoverageCeilingMw===null?'Unavailable':`${num(r.contractCoverageCeilingMw,1)} MW`}<small>{r.boundInclusionReason}</small></td><td>{r.auditNote}<Sources row={r}/></td></tr>)}</tbody></table></div><div className="pa-actions"><File name="power_gap_audit.csv">Complete ledger CSV</File><File name="power_gap_audit.json">JSON</File><File name="power_gap_audit_notes.json">Reviewed notes</File><File name="power_gap_audit_memo.md">Memo</File></div><details className="pa-method"><summary>Locate the audited campuses on a map</summary><Plot title="Audited data-center locations by numerical treatment" height={370} onPointClick={pick} data={(['unmatched','credited','excluded'] as const).map(k=>{const points=shown.filter(r=>group(r)===k&&r.lat!==null);return {type:'scattergeo',name:names[k],mode:'markers',lat:points.map(r=>r.lat),lon:points.map(r=>r.lon),customdata:points.map(r=>r.id),text:points.map(r=>`${r.name}<br>${names[k]}`),hovertemplate:'%{text}<extra></extra>',marker:{size:k==='unmatched'?14:9,color:colors[k],line:{color:'#fff',width:1},opacity:.85}}})} extra={{geo:{scope:'usa',projection:{type:'albers usa'},showland:true,landcolor:'#eef1ea',showsubunits:true,subunitcolor:'#cbd5cf',bgcolor:'transparent'},margin:{l:0,r:0,t:0,b:20},legend:{orientation:'h',y:-.04}}}/><p className="pa-caption">Approximate city/region markers; one location undisclosed. Point size is a treatment marker, not site MW or turbine demand. Natural Earth geography via Plotly, stored locally.</p></details></Panel></div>;
}
