import fs from 'node:fs/promises';
import path from 'node:path';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=path.resolve(import.meta.dirname,'..');
const data=JSON.parse(await fs.readFile(path.join(root,'public/data/research.json'),'utf8'));
const wb=Workbook.create();
const sheets=Object.fromEntries(['Power model','Deployment','Engine allocation','Valuation','Evidence'].map(n=>[n,wb.worksheets.add(n)]));
const put=(s,cell,value)=>s.getRange(cell).values=[[value]];
const formula=(s,cell,text)=>s.getRange(cell).formulas=[[text]];
const accounting='#,##0.0;(#,##0.0);"-"';
function format(s,last=50){s.showGridLines=false;s.getRange(`C2:L${last}`).format.font={name:'Arial',size:10,color:'#17263a'};s.getRange(`C2:L${last}`).format.rowHeight=22;s.getRange(`A1:B${last}`).format.columnWidth=3;s.getRange(`C2:C${last}`).format.columnWidth=48;s.getRange(`D2:G${last}`).format.columnWidth=16;s.getRange(`H2:L${last}`).format.columnWidth=18;s.getRange('C2').format.font={name:'Arial',size:15,bold:true,color:'#17263a'};s.getRange(`D5:G${last}`).setNumberFormat(accounting);}
function header(s,row,labels){s.getRangeByIndexes(row-1,2,1,labels.length).values=[labels];s.getRangeByIndexes(row-1,2,1,labels.length).format={fill:'#17263a',font:{name:'Arial',size:10,bold:true,color:'#ffffff'},rowHeight:25};}
const power=sheets['Power model'];format(power,54);power.tabColor='#17263a';put(power,'C2','FTAI Power operating model');put(power,'C3','Case number: 1 Bear / 2 Base / 3 Bull');put(power,'D3',2);power.getRange('D3').dataValidation={rule:{type:'whole',operator:'between',formula1:1,formula2:3}};power.getRange('D3').format.font.color='#0000ff';put(power,'C4','Case selected');formula(power,'D4','=CHOOSE(D3,"Bear","Base","Bull")');power.getRange('D4').format.font.color='#008000';header(power,5,['FY2027 model output','USD millions / units']);
const params=[
 ['units','Requested deliveries',50,80,100],['capacity','Production capacity',100,100,100],['eligible','Candidate engine pool',200,200,200],['yield','Qualification yield',.7,.7,.7],['asp','FTAI turbine ASP (USD m)',5,6,7],['margin','Turbine gross margin',.25,.35,.4],['serviceUnits','Average serviced units',20,20,20],['serviceRevenue','Annual service revenue / unit (USD m)',.15,.15,.15],['serviceMargin','Service gross margin',.4,.4,.4],['opex','Operating costs (USD m)',40,30,25],['packagingProfit','JV profit after turbine purchases (USD m)',0,0,0],['jvShare','FTAI JV share (unverified)',0,0,0],['tax','Operating cash tax rate',.2,.2,.2],['capex','Capital expenditure (USD m)',100,80,60],['workingCapital','Increase in working capital (USD m)',60,40,30],['advance','FTAI attributable advances (USD m)',0,0,0],['advanceReleased','Advances applied to sales (USD m)',0,0,0],['depreciation','Depreciation (USD m)',10,10,10],['inHorizon','Within-horizon fraction',.4,.65,.8],['deliveryPenalty','Delivery penalty sensitivity',0,0,0],['performancePenalty','Performance penalty sensitivity',0,0,0]
];const pos={};header(power,18,['Scenario inputs','Active','Bear','Base','Bull']);
params.forEach(([key,label,bear,base,bull],i)=>{const row=19+i;pos[key]=`D${row}`;power.getRange(`C${row}:G${row}`).values=[[label,null,bear,base,bull]];formula(power,`D${row}`,`=CHOOSE($D$3,E${row},F${row},G${row})`);power.getRange(`E${row}:G${row}`).format.font.color='#0000ff';if(['yield','margin','serviceMargin','jvShare','tax','inHorizon','deliveryPenalty','performancePenalty'].includes(key))power.getRange(`D${row}:G${row}`).setNumberFormat('0.0%');});
const ps=key=>pos[key];
const powerOutputs=[['Constrained deliveries',`=MIN(${ps('units')},${ps('capacity')},INT(${ps('eligible')}*${ps('yield')}))`],['FTAI turbine revenue',`=D6*${ps('asp')}`],['Turbine gross profit after sensitivity',`=D7*(${ps('margin')}-${ps('deliveryPenalty')}-${ps('performancePenalty')})`],['Service gross profit',`=${ps('serviceUnits')}*${ps('serviceRevenue')}*${ps('serviceMargin')}`],['Operating EBITDA',`=SUM(D8:D9)-${ps('opex')}`],['JV equity profit share',`=${ps('packagingProfit')}*${ps('jvShare')}`],['Attributable earnings proxy','=SUM(D10:D11)'],['Operating cash flow proxy',`=D10-MAX(0,D10-${ps('depreciation')})*${ps('tax')}-${ps('capex')}-${ps('workingCapital')}+${ps('advance')}-${ps('advanceReleased')}`],['Within-horizon earnings proxy',`=D12*${ps('inHorizon')}`]];
powerOutputs.forEach(([label,f],i)=>{put(power,`C${6+i}`,label);formula(power,`D${6+i}`,f);});
put(power,'C42','All commercial inputs are scenarios, not disclosed guidance.');put(power,'C43','JV profit must be after turbine purchases; default attribution is zero.');put(power,'C44','Operating cash proxy excludes JV distributions.');put(power,'C45','FY2027 output is not entirely inside the October 2027 horizon.');put(power,'C46','Penalty pass-through from J&F to FTAI is unknown.');
const deployment=sheets['Deployment'];format(deployment,163);put(deployment,'C2','Customer speed-to-power economics');put(deployment,'C3','Discounted USD / expected operating MW-month');
const dp=[['mw','Installed capacity (MW)',100],['derate','Site output derating',.1],['availability','Availability',.95],['utilization','Utilization',.85],['gas','Gas price (USD/MMBtu LHV)',4],['heat','Mod-1 assumed heat rate (Btu/kWh LHV)',11000],['competitorHeat','Competitor heat rate (Btu/kWh LHV)',8669],['maintenance','Mod-1 maintenance (USD/MWh)',8],['competitorMaintenance','Competitor maintenance (USD/MWh)',6],['capexPerMw','Mod-1 equipment cost (USD m/MW)',.85],['competitorCapexPerMw','Competitor equipment cost (USD m/MW)',.9],['controlPerMw','Mod-1 control cost (USD m/MW)',.08],['competitorControlPerMw','Competitor control cost (USD m/MW)',.08],['redundancy','Redundancy capacity overhead',.1],['fastMonths','Mod-1 equipment readiness (months)',6],['slowMonths','Competitor equipment readiness (months)',18],['readinessMonths','Site readiness (months)',4],['years','Common horizon (years)',5],['discount','Annual discount rate',.1],['contribution','Operating contribution (USD/MW-month)',100000],['gridMonths','Grid readiness (months)',24],['gridRate','Grid electricity (USD/MWh)',80]];
const ds={};header(deployment,12,['Customer assumptions','Value']);dp.forEach(([k,l,n],i)=>{const row=13+i;ds[k]=`D${row}`;put(deployment,`C${row}`,l);put(deployment,`D${row}`,n);deployment.getRange(`D${row}`).format.font.color='#0000ff';if(['derate','availability','utilization','redundancy','discount'].includes(k))deployment.getRange(`D${row}`).setNumberFormat('0.0%');});
header(deployment,40,['Month','Discount','Fast capex','Slow capex','Fast opex','Slow opex','Fast MW-mo','Slow MW-mo','Grid opex','Grid MW-mo']);
const ref=k=>`$${ds[k][0]}$${ds[k].slice(1)}`;const usable=`${ref('mw')}*(1-${ref('derate')})/(1+${ref('redundancy')})`;const mwmo=`(${usable})*${ref('availability')}*${ref('utilization')}`;const fast=`MAX(${ref('fastMonths')},${ref('readinessMonths')})`;const slow=`MAX(${ref('slowMonths')},${ref('readinessMonths')})`;const grid=`MAX(${ref('gridMonths')},${ref('readinessMonths')})`;
for(let i=1;i<=120;i++){const row=40+i;put(deployment,`C${row}`,i);deployment.getRange(`D${row}:L${row}`).formulas=[[
 `=IF(C${row}<=${ref('years')}*12,(1+${ref('discount')})^(-C${row}/12),0)`,
 `=IF(C${row}=MAX(1,ROUNDUP(${fast},0)),${ref('mw')}*(${ref('capexPerMw')}+${ref('controlPerMw')})*1000000*D${row},0)`,
 `=IF(C${row}=MAX(1,ROUNDUP(${slow},0)),${ref('mw')}*(${ref('competitorCapexPerMw')}+${ref('competitorControlPerMw')})*1000000*D${row},0)`,
 `=IF(C${row}>${fast},(${mwmo})*8760/12*(${ref('gas')}*${ref('heat')}/1000+${ref('maintenance')})*D${row},0)`,
 `=IF(C${row}>${slow},(${mwmo})*8760/12*(${ref('gas')}*${ref('competitorHeat')}/1000+${ref('competitorMaintenance')})*D${row},0)`,
 `=IF(C${row}>${fast},(${mwmo})*D${row},0)`,
 `=IF(C${row}>${slow},(${mwmo})*D${row},0)`,
 `=IF(C${row}>${grid},(${mwmo})*8760/12*${ref('gridRate')}*D${row},0)`,
 `=IF(C${row}>${grid},(${mwmo})*D${row},0)`]];}
header(deployment,5,['Customer model result','USD / units']);put(deployment,'C6','Break-even contribution vs competing turbine');formula(deployment,'D6','=IF(SUM(I41:I160)-SUM(J41:J160)>0,MAX(0,(SUM(E41:E160,G41:G160)-SUM(F41:F160,H41:H160))/(SUM(I41:I160)-SUM(J41:J160))),"n.a.")');put(deployment,'C7','Customer NPV advantage (USD m)');formula(deployment,'D7',`=((SUM(I41:I160)-SUM(J41:J160))*${ds.contribution}-(SUM(E41:E160,G41:G160)-SUM(F41:F160,H41:H160)))/1000000`);put(deployment,'C8','Mod-1 fuel + maintenance (USD/MWh)');formula(deployment,'D8',`=${ds.gas}*${ds.heat}/1000+${ds.maintenance}`);put(deployment,'C9','Break-even contribution vs waiting for grid');formula(deployment,'D9','=IF(SUM(I41:I160)-SUM(L41:L160)>0,MAX(0,(SUM(E41:E160,G41:G160)-SUM(K41:K160))/(SUM(I41:I160)-SUM(L41:L160))),"n.a.")');put(deployment,'C36','GE reference: 50 Hz +G4 LHV, not a Texas site guarantee.');put(deployment,'C37','Grid connection capex excluded. Commercial costs are assumed.');put(deployment,'C38','Gas price must use the same LHV energy basis as heat rate.');
const eng=sheets['Engine allocation'];format(eng,36);put(eng,'C2','Engine alternative-use economics');
const ep=[['sale','Turbine sale value (USD m)',6],['acquisition','Candidate acquisition (USD m)',1.5],['conversion','Conversion cost per output (USD m)',2],['testing','Testing cost (USD m)',.3],['workingCapital','Working-capital charge (USD m)',.2],['yield','Qualification yield',.7],['aviationNpv','Aviation receipts less maintenance NPV (USD m)',2.5],['parts','Parts sale value (USD m)',1.6],['maintenanceNpv','Power service NPV (USD m)',.4],['eligible','Candidate engines',200],['repairCapacity','Conversion/repair output capacity',150],['packageCapacity','Packaging capacity',100],['target','Delivery target',100]];const es={};header(eng,14,['Allocation inputs','Value']);ep.forEach(([k,l,n],i)=>{const row=15+i;es[k]=`D${row}`;put(eng,`C${row}`,l);put(eng,`D${row}`,n);eng.getRange(`D${row}`).format.font.color='#0000ff';});eng.getRange(es.yield).setNumberFormat('0.0%');header(eng,5,['Alternative-use output','USD m / units']);const eo=[['Acquisition cost per successful unit',`=${es.acquisition}/${es.yield}`],['Power net value',`=${es.sale}+${es.maintenanceNpv}-D6-${es.conversion}-${es.testing}-${es.workingCapital}`],['Aviation net value',`=${es.aviationNpv}-${es.acquisition}`],['Parts net value',`=${es.parts}-${es.acquisition}`],['Power value over best alternative','=D7-MAX(D8:D9)'],['Constrained annual output',`=MIN(INT(${es.eligible}*${es.yield}),${es.repairCapacity},${es.packageCapacity},${es.target})`],['Feedstock needed for target',`=ROUNDUP(${es.target}/${es.yield},0)`]];eo.forEach(([l,f],i)=>{put(eng,`C${i+6}`,l);formula(eng,`D${i+6}`,f);});put(eng,'C30','All valuation and qualification inputs are assumptions.');put(eng,'C31','Rejected candidates receive zero salvage in this scenario.');put(eng,'C32','FAA aircraft type/age does not establish convertible engine supply.');
const val=sheets.Valuation;format(val,37);put(val,'C2','FTAI sum-of-the-parts sensitivity');put(val,'C3','Observed share price (USD/share; enter dated quote)');put(val,'D3',null);val.getRange('D3').format.fill='#fff2ce';val.getRange('D3').format.font.color='#0000ff';put(val,'C4','Case selected');formula(val,'D4',"='Power model'!D4");val.getRange('D4').format.font.color='#008000';
const vp=[['aerospace','Aerospace FY2027 EBITDA (USD m)',1300],['aerospaceMultiple','Aerospace EV / EBITDA',16],['leasingEv','Residual leasing operating EV (USD m)',1500],['sciEquity','Investment equity proxy (USD m)',401.803],['powerMultiple','Power earnings-proxy multiple',14],['corporateCost','Annual corporate cost (USD m)',50],['corporateMultiple','Corporate cost capitalization',12],['debt','Consolidated bonds before issue costs (USD m)',3496.38],['cash','Unrestricted cash (USD m)',337.195],['preferred','Preferred liquidation value (USD m)',65],['shares','Q2 diluted shares proxy (millions)',104.044113]];const vs={};header(val,12,['Valuation inputs','Value']);vp.forEach(([k,l,n],i)=>{const row=13+i;vs[k]=`D${row}`;put(val,`C${row}`,l);put(val,`D${row}`,n);val.getRange(`D${row}`).format.font.color='#0000ff';});put(val,'C25','Power earnings proxy (USD m)');formula(val,'D25',"='Power model'!D12");val.getRange('D25').format.font.color='#008000';header(val,5,['Valuation output','USD m / per share']);put(val,'C6','Illustrative equity value');formula(val,'D6',`=${vs.aerospace}*${vs.aerospaceMultiple}+${vs.leasingEv}+${vs.sciEquity}+D25*${vs.powerMultiple}-${vs.corporateCost}*${vs.corporateMultiple}-${vs.debt}+${vs.cash}-${vs.preferred}`);put(val,'C7','Illustrative value per share');formula(val,'D7',`=D6/${vs.shares}`);val.getRange('D7').setNumberFormat('$0.00');put(val,'C8','Required Power value at observed price');formula(val,'D8',`=IF(ISNUMBER(D3),D3*${vs.shares}+${vs.debt}-${vs.cash}+${vs.preferred}-${vs.aerospace}*${vs.aerospaceMultiple}-${vs.leasingEv}-${vs.sciEquity}+${vs.corporateCost}*${vs.corporateMultiple},"n.a.")`);put(val,'C9','Required Power earnings proxy');formula(val,'D9',`=IF(ISNUMBER(D8),D8/${vs.powerMultiple},"n.a.")`);put(val,'C28','All enterprise values are mutually exclusive; net debt is deducted once.');put(val,'C29','Investment equity starts at consolidated book value, not SCI fair value.');put(val,'C30','Debt/cash and diluted share proxy: June 2026 SEC filing.');put(val,'C31','Scenario output is not a substantiated price target.');
const evidence=sheets.Evidence;format(evidence,30);put(evidence,'C2','Disclosed financial and operating inputs');put(evidence,'C3','As of October 4, 2026. Source units retained.');header(evidence,5,['Measure','Value','Unit','Basis','Locator','Primary source URL']);data.facts.forEach((f,i)=>{const row=i+6;const source=data.sources.find(s=>s.id===f.source);evidence.getRange(`C${row}:H${row}`).values=[[f.label,f.value,f.unit,f.basis,f.locator,source.url]];});evidence.getRange('C6:C16').format.columnWidth=50;evidence.getRange('E6:G16').format.columnWidth=25;evidence.getRange('H6:H16').format.columnWidth=80;evidence.getRange('C5:H16').format.wrapText=true;evidence.getRange('C6:H16').format.rowHeight=44;put(evidence,'C19','Source documents are linked; no raw PDFs are redistributed.');put(evidence,'C20','Numeric inputs elsewhere distinguish assumptions from these observations.');
power.getRange('D26:G26').setNumberFormat('0.00');
deployment.getRange('D22:D25').setNumberFormat('0.00');
wb.recalculate();
// Verify default output against the independent site model fixtures.
const base=power.getRange('D6:D14').values.map(r=>r[0]);if(Math.abs(base[0]-80)>1e-8||Math.abs(base[6]-139.2)>1e-8||Math.abs(base[7]+6.64)>1e-8)throw Error(`Unexpected base output ${base}`);
put(power,'D3',1);wb.recalculate();if(Math.abs(power.getRange('D6').values[0][0]-50)>1e-8)throw Error('Bear selector failed');put(power,'D3',3);wb.recalculate();if(Math.abs(power.getRange('D6').values[0][0]-100)>1e-8)throw Error('Bull selector failed');put(power,'D3',2);wb.recalculate();
const errors=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:20},maxChars:1500});console.log(errors.ndjson);
const out=path.join(root,'public/data/model-inputs.xlsx');await(await SpreadsheetFile.exportXlsx(wb)).save(out);
const qa=path.join(root,'qa');await fs.mkdir(qa,{recursive:true});
for(const [name,s]of Object.entries(sheets)){const image=await wb.render({sheetName:name,range:name==='Evidence'?'C2:H20':name==='Power model'?'C2:G46':name==='Deployment'?'C2:D38':'C2:D32',scale:1.5,format:'png'});await fs.writeFile(path.join(qa,`${name.replaceAll(' ','-')}.png`),new Uint8Array(await image.arrayBuffer()));}
console.log('Workbook exported and five sheets rendered',out);
